### ISSUE TITLE
Aktuelle Flensburger Webseite als branch einchecken

### ISSUE THREAD

**Issue by rubo77** [freifunk-flensburg/website#10]
@Wlanfr3ak , Könnt ihr bitte die Aktuelle Seite http://freifunk-flensburg.de/ hier einchecken?

Ev. ist dies hier geforkt worden? https://github.com/freifunk-flensburg/website/commit/7836c2fcba4d0665738131454406788de98f8261

**Comment by Wlanfr3ak** [comment]
Ich werde die aktuelle in einem neuen Branch einfügen da die 3 Hauptentwickler diese Version nicht mehr Pflegen. Aktuell klappt aber auch in dieser Version nicht alles reibungslos

**Comment by rubo77** [comment]
Ist jetzt alles aktuell? in welchem Branch?

Ich würde die Seite gerne klonen für ein weiteres Projekt
