### ISSUE TITLE
Preview-Map not updating

### ISSUE THREAD

**Issue by Philzen** [freifunk-flensburg/website#16]
Issues:

- Map is showing an outdated status
- IMO the hash should better be named `#map` instead of `#find-us` 

Let's make a decision whether 

a. to ditch it completely, 
b. re-use the actual map in an iframe or
c.  re-work the whole site to match the design of other communities (i.e. [Hamburg](https://hamburg.freifunk.net/) or [Bremen](http://bremen.freifunk.net) )

**Comment by muellermartin** [comment]
d. Fix the map to use the nodes.json from the "real" map (e.g via cross-domain AJAX request or via proxy script etc.)

**Comment by Wlanfr3ak** [comment]
Map is not more a part of the Page, we have a better map under: map.freifunk-flensburg.de
