### ISSUE TITLE
Karte auf der HP funktioniert nicht (MapQuest deaktiviert Tiles Zugriff)

### ISSUE THREAD

**Issue by Tarnatos** [freifunk-flensburg/website#23]
Moin,

wir ihr ja wisst hat MapQuest den Tiles Zugriff deaktiviert.

Ihr müsst einfach nur einen anderen Tiles Provider der oder einen Proxy einsetzen.

https://github.com/freifunk-flensburg/website/blob/master/assets/javascripts/jquery.main.js
In Zeile 65 patchen.

Z.B. HERE Maps 

Gruß
Tarnatos

**Comment by Wlanfr3ak** [comment]
Ist gefixt bzw. die Map wurde von uns entfernt da sie nicht so detailliert ist wie http://map.freifunk-flensburg.de Vielen Dank für den Hinweis
