### ISSUE TITLE
Spendenaufruf unter Android unlesbar

### ISSUE THREAD

**Issue by svenfl** [freifunk-flensburg/website#29]
Der Spendenaufruf sieht auf Android Geräten ser unleserlich aus Die Formattierung stimmt nicht.
![file1469546597513](https://cloud.githubusercontent.com/assets/11423824/17147375/d99a2776-5362-11e6-808c-15002c0f9517.jpeg)

**Comment by muellermartin** [comment]
In commit 5af99e38 gefixt.

**Comment by muellermartin** [comment]
Ein Umbrechen der Spalten wäre eigentlich besser, daher wird das hier nochmal geöffnet.
