### ISSUE TITLE
Forked

### ISSUE THREAD

**Issue by tigerxy** [freifunk-flensburg/website#6]
Hallo miteinander,

ich hab die Seite für meine eigenen Zwecke umgeschrieben. Dazu hab ich das ganze in Grunt gepackt. Damit sind dann auch diese etlichen includes zu den php Seiten in /contents überflüssig und alles wird auch noch gleich komprimiert. Vielleicht habt ihr ja Lust das zu übernehmen.

Leider habt ihr keine Lizenz angegeben, darum hoffe ich, dass es so ok ist wenn ich das so verwende. Wäre nett wenn ihr mir kurz Rückmeldung geben könntet. Soll ich noch einen Link zu eurer Seite mit einbauen?

Hier das ganze Live: http://www.freifunk-ebs.de/

Gruß

**Comment by malteriechmann** [comment]
Hallo,

ich freue mich, wenn die Webseite nicht nur von Freifunk Flensburg genutzt wird, sondern auch von anderen Gemeinschaften weitergetragen wird.

Wir haben uns extra gegen Grunt oder Gulp entschieden, denn die Seite sollte für jede_n erweiterbar sein, auch ohne große Kenntnisse in der Frontend-Webentwicklung. Persönlich hätte ich auch gern etwas anders gearbeitet, aber der Gedanke, dass die Webseite von allen geändert werden konnte, lag mir näher.

Danke für dein Nachfragen und das Informieren. Vielleicht gibt es ja auch bald mal eine Version 2, das eine oder andere Feature haben wir schon im Kopf.

Viele Grüße,
Malte
