### ISSUE TITLE
Lizenzierung der Seite

### ISSUE THREAD

**Issue by roikiermedia** [freifunk-flensburg/website#7]
Unsere Seite und dieses Repo erfreut sich glücklicherweise in der Freifunk-Community (und auch außerhalb) großer Beliebtheit. Die Forks vermehren sich, das Presseteam erhält stetig Nutzungsanfragen über Mail und auch schon einige Nutzungen ohne Verweis auf uns wurden gefunden. ;) Um für alle diesen Vorgang etwas zu erleichtern und um unser Postfach auszudünnen würde ich mich gerne mit allen Autoren auf eine Lizenz einigen.

Die Header-Bilder von @Wlanfr3ak standen bereits unter Creative Commons Attribution 3.0 (CC-BY 3.0). Ich habe mich bei der Erstellung der Seite entschlossen meine verwendeten Bilder und Grafiken unter der selben Lizenz zu veröffentlichen.

Die MIT-ähnliche Lizenz der Javascript library Leaflet, welche wir zur Darstellung der Karte benutzen, ist hier zu finden: https://github.com/Leaflet/Leaflet/blob/master/LICENSE
Das jQuery Plugin particleground (https://github.com/jnicol/particleground) welches wir für die Visualisierung eines Meshnetzwerkes verwenden steht unter einer MIT-Lizenz. 

Eine Übersicht über die häufigsten OpenSource-Lizenzen findet ihr unter http://choosealicense.com/.
Für Assets, Texte, Dokumentationen ist auch eine Creative Commons Lizenz in Erwägung zu ziehen. Verschiedene Lizenzen könnt ihr hier unter https://creativecommons.org/choose/?lang=en wählen. Für Software selbst sind diese Lizenzen jedoch ungeeignet. Weiter Informationen dazu unter https://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F .

Ich denke mal ihr wisst sonst alle was ihr selbst an dieser Seite mit gestaltet habt, oder schaut dies in den Commits nach.

---

Meine Meinung:
Persönlich würde ich mich vollkommen mit einer MIT-Lizenz zufrieden geben. Eine GPL fände ich sogar noch besser. Einen etwas seltsamen Wunsch hätte ich jedoch zu allen Lizenzen:
Momentan gibt es kaum Lizenzen die eine militärische Verwendung ausschließen. Ich glaube zwar nicht das irgendeine Armee an einer Freifunkseite interessiert ist, halte das Thema aufgrund jüngster Entwicklungen im Bereich Android (http://blog.fefe.de/?ts=abda600a) jedoch für wichtig. Das ist, wie gesagt, weniger ein Problem das uns direkt betrifft, als mehr eine pazifistische Politik die ich gerne fahren möchte. Und den einen Satz schreibe ich euch auch gerne in das jeweilige File.

Frohes Lesen!

**Comment by roikiermedia** [comment]
Nachtrag:
Anscheinend kann man immer nur einen Nutzer assignen.
Dieses Issue betrifft natürlich hauptsächlich @malteriechmann, @spralexx, @Wlanfr3ak und mich. Natürlich sind aber auch alle anderen Meinungen von der Community willkommen.

**Comment by spralexx** [comment]
+1 für deinen vorschlag. also von mir aus gerne gpl

**Comment by malteriechmann** [comment]
Kenne mich zu wenig mit Lizenzen aus, als das ich eine qualifizierte Meinung geben könnte. Hauptsache jede_r darf es kostenfrei und ohne Rückverweis benutzen.

**Comment by roikiermedia** [comment]
Okay, vielen Dank für eure Rückmeldung. Ich bestücke das Repo innerhalb der nächsten Stunden mit einer passenden Lizenz.

**Comment by Wlanfr3ak** [comment]
Also meine Bilder lasse ich unter der selben Lizenz wie sie jetzt sind, da die Communitys ja sehr warscheinlich Ihre eigenen Bilder nutzen wollen.

**Comment by roikiermedia** [comment]
Das tue ich auch. Die Assets sind von einer neuen Softwarelizenz nicht betroffen.
