### ISSUE TITLE
Community Hinweise werden nicht angezeigt

### ISSUE THREAD

**Issue by roikiermedia** [freifunk-flensburg/website#8]
Ich habe gerade die Texte aktualisiert und vom Server gepullt. (Aktuell Commit https://github.com/freifunk-flensburg/website/commit/d550b53c18548740b4aa609a98d1e82390d295ab)
Bei mir (Chrome 41, Mac OS X 10.9 & Chrome 41, Android 5.1) werden die Hinweise zu verschiedenen Firmwares nicht angezeigt, nachdem eine Version gewählt wurde.

**Comment by Wlanfr3ak** [comment]
Wer hat das mit dem NordLab Text abgesprochen ?

**Comment by malteriechmann** [comment]
@roikiermedia Es sieht so aus, als hättest du die Datei "jquery.main.js" nicht aktualisiert.

**Comment by spralexx** [comment]
@Wlanfr3ak falcher issue

@malteriechmann @roikiermedia ich habdas grade mal local probiert. geht auch nicht...

**Comment by spralexx** [comment]
"@malteriechmann @roikiermedia ich habdas grade mal local probiert. geht auch nicht..."

ich nehme alles zurück und behaupte das gegenteil.

**Comment by malteriechmann** [comment]
@spralexx Da bin ich aber beruhigt ,)

**Comment by spralexx** [comment]
mein browser hatte noch die alte version von jquery.main.js gecached

**Comment by spralexx** [comment]
der server liefert die neue datei nicht aus. ich guck mal, was da los ist.

**Comment by roikiermedia** [comment]
@spralexx Ich habe bei mir auch den Cache schon geleert gehabt. Machte er trotzdem nicht.

@Wlanfr3ak Den hat ein Mitglied des Presseteams (huhu, der hier!) nach bestem Wissen und Gewissen geschrieben. Solltet ihr euch damit nicht richtig dargestellt fühlen, schickt mir bitte einen neuen Text in nicht all zu lang, oder gebt mir Stichpunkte was geändert werden soll. Die Änderungen werden dann postwendend eingearbeitet.

**Comment by spralexx** [comment]
@roikiermedia ja, der server gibt die alte datei raus... wenn du's local machst und den cache geleert hast, gehts.

**Comment by spralexx** [comment]
@Wlanfr3ak hat den domainrecord geändert. daher konnte es nicht gehen.

**Comment by roikiermedia** [comment]
Nene, den Issue haben wir immer noch im Bezug auf Freifunk-Flensburg.de. Nur hat sich gerade die Lösung geändert.

**Comment by Wlanfr3ak** [comment]
Schick mir nen Text ich Pflege den dann ein.
Am 22.04.2015 20:51 schrieb "Thorben Dittmar" <notifications@github.com>:

**Comment by roikiermedia** [comment]
Joa, zieh einfach dir den besagten Commit https://github.com/freifunk-flensburg/website/commit/d550b53c18548740b4aa609a98d1e82390d295ab und fertig ist die Kiste.
